---
- name: swap off
  shell: swapoff -a

- name: disable SELinux
  lineinfile:
    path: /etc/selinux/config
    line: SELINUX=disabled
    regexp: SELINUX=enforcing

- name: add kubernetes node hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item]['ansible_facts']['fqdn'] }}"
  with_items: 
  - "{{ groups['master'] }}"
  - "{{ groups['worker'] }}"

- name: install iproute-tc package
  dnf:
    name: iproute-tc
    state: present

- name: disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: false

- name: modules config insert
  lineinfile:
    path: /etc/modules-load.d/k8s.conf
    line: "{{ item }}"
    create: yes
    state: present
  with_items:
    - overlay
    - br_netfilter

- name: modprobe
  shell: "modprobe {{ item }}"
  with_items:
    - overlay
    - br_netfilter

- name: kernel parameter add
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: "{{ item }}"
    create: yes
    state: present
  with_items:
    - "net.bridge.bridge-nf-call-iptables  = 1"
    - "net.ipv4.ip_forward                 = 1"
    - "net.bridge.bridge-nf-call-ip6tables = 1" 

- name: kernel parameter reload
  shell: sysctl --system

- name: crio yum repo add
  shell: curl -L -o /etc/yum.repos.d/devel-kubic-libcontainers-stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/devel:kubic:libcontainers:stable.repo
  when: crio

- name: crio yum repo add
  shell: "curl -L -o /etc/yum.repos.d/devel-kubic-libcontainers-stable-cri-o-{{ crio_version }}.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{ crio_version }}/CentOS_8/devel:kubic:libcontainers:stable:cri-o:{{ crio_version }}.repo"
  when: crio

- name: crio package install
  dnf:
    name: cri-o
    state: present
  when: crio

- name: crio enable and start
  systemd:
    name: crio
    state: started
    enabled: true
  when: crio
